// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onPressureChange();
void onPressure2Change();
void onRawlevelreading1Change();
void onRawlevelreading2Change();

float pressure;
float pressure2;
int rawlevelreading1;
int rawlevelreading2;

void initProperties(){

  ArduinoCloud.addProperty(pressure, READWRITE, 1 * SECONDS, onPressureChange);
  ArduinoCloud.addProperty(pressure2, READWRITE, 1 * SECONDS, onPressure2Change);
  ArduinoCloud.addProperty(rawlevelreading1, READWRITE, 1 * SECONDS, onRawlevelreading1Change);
  ArduinoCloud.addProperty(rawlevelreading2, READWRITE, 1 * SECONDS, onRawlevelreading2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
